### ISSUE TITLE
NSX T Exporter

### ISSUE THREAD

**Issue by sudhakars1304** [arthur-ehrle/nsx-exporter#1]
We are trying to deploy Prometheus & Grafana for NSX T Monitoring and we are unable to download the NSX T Exporter Image on it. 

Please help us providing the NSX T Image for the NSX T Exporter.

**Comment by arthur-ehrle** [comment]
Did you try to pull the image with the tag "1.1.1" that you can see on docker hub with "docker pull aehr/nsxv3-exporter:1.1.1" ?
Or you can build the image by yourself using the Dockerfile that I just provided.

**Comment by sudhakars1304** [comment]
Thank you we have downloaded the image. Will engage you if we face any issue when deploying in K8s
